export default {
    nodes: [
        // { id: "ARDUINO A", group: 1 },
        // { id: "ARDUINO B", group: 2 },
        // { id: "ARDUINO C", group: 3 },
        // { id: "A1", group: 1 },
        // { id: "A2", group: 1 },
        // { id: "A3", group: 1 },
        // { id: "A4", group: 1 },
        // { id: "A5", group: 1 },
        // { id: "A6", group: 1 },
        // { id: "B1", group: 2 },
        // { id: "B2", group: 2 },
        // { id: "B3", group: 2 },
        // { id: "B4", group: 2 },
        // { id: "B5", group: 2 },
        // { id: "B6", group: 2 },
        // { id: "C1", group: 3 },
        // { id: "C2", group: 3 },
        // { id: "C3", group: 3 },
        // { id: "C4", group: 3 },
        // { id: "C5", group: 3 },
        // { id: "C6", group: 3 },
    ],
    links: [
        // { source: "ARDUINO A", target: "ARDUINO B", value: 1 },
        // { source: "ARDUINO A", target: "ARDUINO C", value: 1 },
        // { source: "ARDUINO B", target: "ARDUINO C", value: 1 },
        // { source: "A1", target: "ARDUINO A", value: 1 },
        // { source: "B1", target: "ARDUINO B", value: 1 },
        // { source: "C1", target: "ARDUINO C", value: 1 },
        // { source: "A2", target: "ARDUINO A", value: 1 },
        // { source: "B2", target: "ARDUINO B", value: 1 },
        // { source: "C2", target: "ARDUINO C", value: 1 },
    ]
};
